/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVisionRouteImport } from './routes/_app.vision'
import { Route as AppStudyRouteImport } from './routes/_app.study'
import { Route as AppSelfCareRouteImport } from './routes/_app.self-care'
import { Route as AppRoutineRouteImport } from './routes/_app.routine'
import { Route as AppNoRulesRouteImport } from './routes/_app.no-rules'
import { Route as AppMediaRouteImport } from './routes/_app.media'
import { Route as AppMealsRouteImport } from './routes/_app.meals'
import { Route as AppHealthRouteImport } from './routes/_app.health'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisionRoute = AppVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppSelfCareRoute = AppSelfCareRouteImport.update({
  id: '/self-care',
  path: '/self-care',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutineRoute = AppRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => AppRoute,
} as any)
const AppNoRulesRoute = AppNoRulesRouteImport.update({
  id: '/no-rules',
  path: '/no-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/health': typeof AppHealthRoute
  '/meals': typeof AppMealsRoute
  '/media': typeof AppMediaRoute
  '/no-rules': typeof AppNoRulesRoute
  '/routine': typeof AppRoutineRoute
  '/self-care': typeof AppSelfCareRoute
  '/study': typeof AppStudyRoute
  '/vision': typeof AppVisionRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/health': typeof AppHealthRoute
  '/meals': typeof AppMealsRoute
  '/media': typeof AppMediaRoute
  '/no-rules': typeof AppNoRulesRoute
  '/routine': typeof AppRoutineRoute
  '/self-care': typeof AppSelfCareRoute
  '/study': typeof AppStudyRoute
  '/vision': typeof AppVisionRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/meals': typeof AppMealsRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/no-rules': typeof AppNoRulesRoute
  '/_app/routine': typeof AppRoutineRoute
  '/_app/self-care': typeof AppSelfCareRoute
  '/_app/study': typeof AppStudyRoute
  '/_app/vision': typeof AppVisionRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/health'
    | '/meals'
    | '/media'
    | '/no-rules'
    | '/routine'
    | '/self-care'
    | '/study'
    | '/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/health'
    | '/meals'
    | '/media'
    | '/no-rules'
    | '/routine'
    | '/self-care'
    | '/study'
    | '/vision'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/health'
    | '/_app/meals'
    | '/_app/media'
    | '/_app/no-rules'
    | '/_app/routine'
    | '/_app/self-care'
    | '/_app/study'
    | '/_app/vision'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vision': {
      id: '/_app/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof AppVisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/study': {
      id: '/_app/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/self-care': {
      id: '/_app/self-care'
      path: '/self-care'
      fullPath: '/self-care'
      preLoaderRoute: typeof AppSelfCareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routine': {
      id: '/_app/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof AppRoutineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/no-rules': {
      id: '/_app/no-rules'
      path: '/no-rules'
      fullPath: '/no-rules'
      preLoaderRoute: typeof AppNoRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meals': {
      id: '/_app/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHealthRoute: typeof AppHealthRoute
  AppMealsRoute: typeof AppMealsRoute
  AppMediaRoute: typeof AppMediaRoute
  AppNoRulesRoute: typeof AppNoRulesRoute
  AppRoutineRoute: typeof AppRoutineRoute
  AppSelfCareRoute: typeof AppSelfCareRoute
  AppStudyRoute: typeof AppStudyRoute
  AppVisionRoute: typeof AppVisionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHealthRoute: AppHealthRoute,
  AppMealsRoute: AppMealsRoute,
  AppMediaRoute: AppMediaRoute,
  AppNoRulesRoute: AppNoRulesRoute,
  AppRoutineRoute: AppRoutineRoute,
  AppSelfCareRoute: AppSelfCareRoute,
  AppStudyRoute: AppStudyRoute,
  AppVisionRoute: AppVisionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
